# Generated by Django 6.0.7 on 2026-09-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_link",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на платежную страницу Stripe",
                max_length=400,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор сессии оплаты в Stripe",
                max_length=255,
                null=True,
                verbose_name="ID сессии Stripe",
            ),
        ),
    ]
