# Generated by Django 6.0.7 on 2026-09-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payment_payment_link_payment_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_amount",
            field=models.PositiveIntegerField(default=0, verbose_name="Сумма оплаты"),
        ),
    ]
