# Generated by Django 6.0.7 on 2026-09-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_payment_payment_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_link",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на платежную страницу Stripe",
                max_length=1000,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
    ]
